# Pandas 실습

### 1. 실습 데이터 실습
서울시 지하철 호선별 승하차 인원

In [6]:
import warnings
warnings.filterwarnings(action='ignore')

import pandas as pd
import numpy as np

In [18]:
# 데이터 로딩
df = pd.read_csv('data/CARD_SUBWAY_MONTH_202605.csv')

In [26]:
# 데이터 로딩
df = pd.read_csv('data/CARD_SUBWAY_MONTH_202605.csv',index_col=False)

In [28]:
df.head()

       사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
0  20260501  5호선   방이    5527    5357  20260504
1  20260501  5호선  둔촌동   10441    9979  20260504
2  20260501  5호선  상일동   10541    9932  20260504
3  20260501  5호선   고덕    7456    7257  20260504
4  20260501  5호선   명일    6377    6251  20260504

## 2. 데이터 탐색

In [38]:
# 상위 5개의 데이터 조회
df.head(5)

       사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
0  20260501  5호선   방이    5527    5357  20260504
1  20260501  5호선  둔촌동   10441    9979  20260504
2  20260501  5호선  상일동   10541    9932  20260504
3  20260501  5호선   고덕    7456    7257  20260504
4  20260501  5호선   명일    6377    6251  20260504

In [66]:
# 데이터프레임의 형태로 조회
df.shape

(19131, 6)

In [40]:
# 하위 데이터 10개 조회
df.tail(10)

           사용일자  노선명                역명  승차총승객수  하차총승객수      등록일자
19121  20260531  8호선                문정    7350    7431  20260603
19122  20260531  8호선                장지   10401    9980  20260603
19123  20260531  8호선                복정    5988    5340  20260603
19124  20260531  8호선                산성    3611    3915  20260603
19125  20260531  8호선  남한산성입구(성남법원.검찰청)    6905    6413  20260603
19126  20260531  8호선             단대오거리    6782    6559  20260603
19127  20260531  8호선                신흥    3732    3895  20260603
19128  20260531  8호선                수진    4223    3812  20260603
19129  20260531  8호선                모란    3406    2806  20260603
19130  20260531  8호선               남위례    4515    4530  20260603

In [44]:
# 데이터의 사분면수, 표준편차, 분산 등 통계자료를 조회
df.describe()

               사용일자         승차총승객수         하차총승객수          등록일자
count  1.913100e+04   19131.000000   19131.000000  1.913100e+04
mean   2.026052e+07   11811.350740   11759.563640  2.026053e+07
std    8.944833e+00   11836.994181   12011.261965  2.614125e+01
min    2.026050e+07       1.000000       0.000000  2.026050e+07
25%    2.026051e+07    4125.000000    4022.000000  2.026051e+07
50%    2.026052e+07    8396.000000    8135.000000  2.026052e+07
75%    2.026052e+07   15701.500000   15507.500000  2.026053e+07
max    2.026053e+07  101927.000000  115875.000000  2.026060e+07

In [46]:
# 데이터의 데이터타입, 데이터 갯수 등을 조회
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19131 entries, 0 to 19130
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용일자    19131 non-null  int64
 1   노선명     19131 non-null  object
 2   역명      19131 non-null  object
 3   승차총승객수  19131 non-null  int64
 4   하차총승객수  19131 non-null  int64
 5   등록일자    19131 non-null  int64
dtypes: int64(4), object(2)
memory usage: 896.9+ KB

In [56]:
# '노선명' 컬럼이 가지고 있는 데이터의 종류를 확인, 중복되지 않은 데이터 갯수와 데이터 확인
df['노선명'].nunique() # 27
df['노선명'].unique() # array(['5호선', '4호선',... dtype=object)

array(['5호선', '4호선', '경의선', '3호선', '2호선', '1호선', '경인선', '경춘선', '공항철도 1호선',
       '안산선', '과천선', '분당선', '서해선', '수인선', '신림선', '우이신설선', '일산선', '장항선',
       '중앙선', '경원선', '경부선', '경강선', '9호선2~3단계', '9호선', '8호선', '7호선', '6호선'],
      dtype=object)

In [64]:
# '역명' 컬럼이 가지고 있는 데이터의 종류를 확인, 중복되지 않은 데이터 갯수와 데이터 확인
df['역명'].nunique() # 528
df['역명'].unique() # array([''방이, '둔촌동',... dtype=object)

array(['방이', '둔촌동', '상일동', '고덕', '명일', '굽은다리(강동구민회관앞)', '길동', '강동',
       '천호(풍납토성)', '광나루(장신대)', '아차산(어린이대공원후문)', '군자(능동)', '장한평', '답십리',
       '마장', '왕십리(성동구청)', '행당', '신금호', '청구', '동대문역사문화공원(DDP)', '을지로4가',
       '종로3가', '광화문(세종문화회관)', '서대문', '충정로(경기대입구)', '애오개', '공덕', '마포',
       '여의나루', '여의도', '신길', '영등포시장', '영등포구청', '양평', '오목교(목동운동장앞)', '목동',
       '신정(은행정)', '까치산', '화곡', '우장산', '발산', '마곡', '송정', '김포공항', '개화산',
       '방화', '남태령', '사당', '총신대입구(이수)', '동작(현충원)', '이촌(국립중앙박물관)', '신용산',
       '삼각지(전쟁기념관)', '숙대입구(갈월)', '서울역', '회현(남대문시장)', '명동', '충무로', '동대문',
       '혜화', '한성대입구(삼선교)', '성신여대입구(돈암)', '길음', '미아사거리', '미아(서울사이버대학)',
       '수유(강북구청)', '쌍문', '창동', '노원', '상계', '한국항공대', '불암산', '오금', '경찰병원',
       '가락시장', '수서', '일원', '대청', '학여울', '대치', '도곡', '매봉', '양재(서초구청)',
       '남부터미널(예술의전당)', '교대(법원.검찰청)', '고속터미널', '잠원', '신사', '압구정', '옥수',
       '금호', '약수', '동대입구', '을지로3가', '안국', '경복궁(정부서울청사)', '독립문', '무악재',
       '홍제', '녹번', '불광', '연신내', '구파발', '지축', '용두(동대문구청)', '신정네거리', '양천구청',
       '도림천', '신설동', '신답', '용답', '아현', '이대', '신촌', '홍대입구', '합정', '당산',
       '문래', '신도림', '대림(구로구청)', '구로디지털단지', '신대방', '신림', '봉천',
       '서울대입구(관악구청)', '낙성대(강감찬)', '방배', '서초', '강남', '역삼', '선릉',
       '삼성(무역센터)', '종합운동장', '잠실새내', '잠실(송파구청)', '잠실나루', '강변(동서울터미널)',
       '구의(광진구청)', '건대입구', '성수', '뚝섬', '한양대', '상왕십리', '신당', '을지로입구', '시청',
       '동묘앞', '청량리(서울시립대입구)', '제기동', '종로5가', '종각', '강매', '행신', '능곡', '곡산',
       '백마', '풍산', '일산', '탄현', '야당', '운정', '금릉', '금촌', '월롱', '파주', '문산',
       '임진강', '운천', '개봉', '오류동', '역곡', '부천', '송내', '부평', '백운', '동암', '주안',
       '제물포', '동인천', '인천', '구일', '소사', '부개', '간석', '도원', '온수(성공회대입구)',
       '중동', '도화', '신내', '갈매', '별내', '퇴계원', '사릉', '금곡', '평내호평', '천마산',
       '마석', '대성리', '청평', '상천', '가평', '굴봉산', '백양리', '강촌', '김유정', '남춘천',
       '춘천', '디지털미디어시티', '산본', '마곡나루(서울식물원)', '계양', '검암', '청라국제도시', '운서',
       '공항화물청사', '인천공항1터미널', '인천공항2터미널', '영종', '선바위', '경마공원', '대공원', '과천',
       '정부과천청사', '인덕원', '평촌', '범계', '한티', '구룡', '개포동', '대모산입구', '수원',
       '서울숲', '압구정로데오', '강남구청', '선정릉', '가천대', '태평', '모란', '야탑', '서현',
       '수내', '정자', '미금', '오리', '이매', '보정', '죽전', '구성', '신갈', '기흥', '상갈',
       '청명', '영통', '망포', '매탄권선', '수원시청', '매교', '원종', '부천종합운동장', '고색',
       '오목천', '어천', '야목', '사리', '달월', '월곶', '소래포구', '인천논현', '호구포',
       '남동인더스파크', '원인재', '연수', '송도', '인하대', '숭의', '신포', '샛강', '대방',
       '서울지방병무청', '보라매', '보라매공원', '보라매병원', '당곡', '서원', '서울대벤처타운',
       '관악산(서울대)', '대야미', '반월', '상록수', '한대앞', '중앙', '고잔', '초지', '안산',
       '신길온천', '정왕', '오이도', '수리산', '북한산우이', '솔밭공원', '4.19민주묘지', '가오리',
       '화계', '삼양', '삼양사거리', '솔샘', '북한산보국문', '정릉', '보문', '원흥', '삼송', '원당',
       '화정', '대곡', '백석', '마두', '정발산', '주엽', '대화', '봉명', '쌍용(나사렛대)', '아산',
       '탕정', '배방', '온양온천', '신창(순천향대)', '회기', '중랑', '상봉', '망우', '양원', '구리',
       '도농', '양정', '덕소', '도심', '팔당', '운길산', '양수', '신원', '국수', '아신', '오빈',
       '원덕', '용문', '지평', '수색', '가좌', '서강대', '효창공원앞', '연천', '전곡', '청산',
       '소요산', '동두천', '보산', '동두천중앙', '지행', '덕정', '덕계', '양주', '녹양', '가능',
       '의정부', '회룡', '망월사', '도봉산', '도봉', '방학', '녹천', '월계', '광운대', '석계',
       '신이문', '외대앞', '응봉', '한남', '서빙고', '광명', '서동탄', '당정', '천안', '두정',
       '직산', '성환', '평택', '평택지제', '서정리', '송탄', '진위', '오산', '오산대', '세마',
       '병점', '세류', '독산', '화서', '성균관대', '의왕', '군포', '금정', '명학', '안양', '관악',
       '석수', '금천구청', '가산디지털단지', '구로', '영등포', '노량진', '용산', '남영', '성남',
       '여주', '세종대왕릉', '부발', '이천', '신둔도예촌', '곤지암', '초월', '경기광주', '삼동',
       '판교', '중앙보훈병원', '둔촌오륜', '올림픽공원(한국체대)', '한성백제', '송파나루', '석촌',
       '석촌고분', '삼전', '봉은사', '삼성중앙', '언주', '신논현', '사평', '신반포', '구반포',
       '흑석(중앙대입구)', '노들', '국회의사당', '선유도', '신목동', '염창', '등촌', '증미', '가양',
       '양천향교', '신방화', '공항시장', '개화', '남위례', '수진', '신흥', '단대오거리',
       '남한산성입구(성남법원.검찰청)', '산성', '복정', '장지', '문정', '송파', '몽촌토성(평화의문)',
       '강동구청', '암사', '암사역사공원', '천왕', '광명사거리', '철산', '남구로', '신풍', '신대방삼거리',
       '장승배기', '상도', '숭실대입구(살피재)', '남성', '이수', '내방', '반포', '논현', '학동',
       '청담', '자양(뚝섬한강공원)', '어린이대공원(세종대)', '중곡', '용마산(용마폭포공원)', '사가정',
       '면목', '중화', '먹골', '태릉입구', '공릉(서울과학기술대)', '하계', '중계', '마들', '수락산',
       '장암', '봉화산(서울의료원)', '화랑대(서울여대입구)', '돌곶이', '상월곡(한국과학기술연구원)',
       '월곡(동덕여대)', '고려대(종암)', '안암(고대병원앞)', '창신', '버티고개', '한강진', '이태원',
       '녹사평(용산구청)', '대흥(서강대앞)', '광흥창(서강)', '상수', '망원', '마포구청',
       '월드컵경기장(성산)', '증산(명지대앞)', '새절(신사)', '구산', '독바위', '역촌', '응암',
       '하남검단산', '하남시청(덕풍·신장)', '하남풍산', '미사', '강일', '마천', '거여', '개롱'],
      dtype=object)

In [76]:
# '범주형' - value_counts() : 몇번이나 반족(등장)하는가 확인
# '노선명' 컬럼이 가지고 있는 데이터 분포 확인
df['노선명'].value_counts()

노선명
5호선         1736
2호선         1550
7호선         1302
경부선         1209
6호선         1193
분당선         1080
3호선         1053
경원선         1021
경의선          843
4호선          806
9호선          775
중앙선          651
경인선          620
경춘선          589
8호선          589
수인선          558
공항철도 1호선     434
안산선          403
우이신설선        403
9호선2~3단계     403
경강선          372
신림선          341
일산선          332
1호선          310
과천선          248
장항선          217
서해선           93
Name: count, dtype: int64

## 3. 데이터 정렬

In [95]:
# '승차총승객수' 기준으로 데이터 정렬 (내림차순)
df.sort_values(by=['승차총승객수'],ascending=False)

           사용일자  노선명        역명  승차총승객수  하차총승객수      등록일자
118    20260501  2호선      홍대입구  101927  115875  20260504
8668   20260515  2호선  잠실(송파구청)  100436   98646  20260518
682    20260502  2호선      홍대입구  100394  111108  20260505
8674   20260515  2호선        강남   98157   96835  20260518
13541  20260522  1호선       서울역   97514   98036  20260525
...         ...  ...       ...     ...     ...       ...
16079  20260527  경의선       서울역       1       0  20260530
16080  20260527  경의선        신촌       1       0  20260530
2063   20260504  일산선        지축       1       0  20260507
15461  20260526  경원선        창동       1       0  20260529
16688  20260528  6호선       연신내       1       0  20260531

[19131 rows x 6 columns]